---
title: "R Notebook"
output: html_notebook
---

Reading data
```{r}
data <- read.csv("/media/newhd/joao-souza/projects/GEMINI/TOC_M4/toc_data_testing_models_R.csv",
                 na.strings = c("",'NA'))

#### Fracture data from my github
fractures <- read.csv("https://raw.githubusercontent.com/souzajvp/gemini/main/kts_modified/fracture_variables.csv")
#### Insert columns from fractures into the general dataframe
data$long_y_n <- fractures$long_y_n

data$classification <- fractures$classification
```

The new KTS calculation will have modifications on the way to determine wether a patient has serious injuries.
It will consider ED disposition, presence of longbone fractures, need for surgery, multiple injuries, and TBI

## Coding Age
```{r}
## recoding age for KTS 
##### Less than 5 (1); 5 to 55 (2); more than 55 (1)
data$age_kts <- as.numeric(as.character(cut(data$age, breaks=c(-1, 4, 55, 500), labels=c(1 , 2, 1))))
```

## Coding systolic blood pressure

```{r}
## recoding systolic blood pressure for kts 
##### 0 (1); 1 to 49 (2); 50 to 89 (3); more than 89 (4)
data$sbp_arred_kts <- as.numeric(as.character(cut(data$sbp_arred, breaks=c(-1,0,49,89,500), labels=c(1,2,3,4))))
```

## Coding respiratory rate
```{r}
## recoding respiratory rate for kts ->
data$rr_arred_kts  <- as.numeric(as.character(cut(data$rr_arred, breaks=c(-Inf,8,29,Inf), labels=c(1,3,2))))
```

## Coding avpu
```{r}
## recoding avpu_arred for kts -> First I replace the codes for the actual classes in the codebook
data$avpu_arred_kts <- car::recode(data$avpu_arred,"0='Alert'; 1='Responds to verbal stimuli only';
                                   2='Responds to painful stimuli only';
                                   3='Unresponsive'")
# then I assign the values --> Alert (4); Verbal (3); Painful (2); Unresponsive (1)
data$avpu_arred_kts <- as.numeric(car::recode(data$avpu_arred_kts,"'Alert'=4; 'Responds to verbal stimuli only'=3;
                                   'Responds to painful stimuli only'=2; 'Unresponsive'=1"))
```

## Serious injury

```{r}
# Here I check if There is indication for surgery; If the patient is either in O.R or ICU; If there were fractures on either Long bones or Spine; If there are multiple injuries; If there is TBI
# This is then set in the serious_injury_kts variable
data$serious_injury_kts <- (data$surg_1 == 1) | (data$dispo_loc %in% c(0,1)) | (data$long_y_n %in% c("Long", "Spine")) | (data$classification == "multiple") | (data$tbiyn == 1)
# Next, the values that were false became NA, which then are filled with FALSE
data$serious_injury_kts[is.na(data$serious_injury_kts)] <- FALSE
# Finally, I replace TRUE and FALSE for 1 and 2, respectively
data$serious_injury_kts <- car::recode(data$serious_injury_kts, "TRUE=1;FALSE=2")

```

## Creating the kts_mod variable
```{r}
data$kts_mod <- (data$age_kts + data$sbp_arred_kts + data$rr_arred_kts + data$avpu_arred_kts + data$serious_injury_kts)

table(data$kts_mod)
```

